[server]
hostname = "localhost"
port = 8080

[redis]
[redis.server]
host = "localhost"
port = 6379
db = 0
maxRetriesPerRequest = 4
[redis.pool]
maxPoolSize = 100
runCloseIdleConnMillis = 60000

[judger]
webSocketPath = "/judger"
tokenExpire = 5000
listenTimeoutSec = 10
reportInterval = 3000
lifeCheckInterval = 6000
tokenGcInterval = 300000
tokenGcExpire = 300000
processPingInterval = 2000
processCheckInterval = 3000
