[server]
hostname = "localhost"
port = 8080

[redis]
[redis.server]
host = "localhost"
port = 6379
db = 0
maxRetriesPerRequest = 4
[redis.pool]
maxPoolSize = 10
runCloseIdleConnMillis = 60000

[judger]
[judger.ws]
port = 9000
tokenExpire = 20000
reportInterval = 1000
lifeCheckInterval = 3000
clearTokenInterval = 300000
badTokenLifeTime = 300000